# serverless.yml

service: ServerlessExample

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true
  RDSVPC:
    securityGroupIds:
      - sg-xxxxxxxx
    subnetIds:
      - subnet-xxxxxxxx
      - subnet-xxxxxxxx
  authorizer:
    name: authorizer
    type: TOKEN
    identitySource: method.request.header.Authorization
    identityValidationExpression: Bearer (.*)

provider:
  name: aws
  runtime: nodejs6.10
#  stage: dev (default)
  region: ap-northeast-1
  apiKeys:
    - ServerlessExample
  memorySize: 128

package:
  individually: true
  exclude:
    - .git/**

functions:
  authorizer:
    handler: authorizer.handler
    name: ${ self:service }Authorizer-${ self:provider.stage }
    description: Authorizer.

  hello:
    handler: hello.handler
    name: ${ self:service }Hello-${ self:provider.stage }
    description: Get user leave history.
    vpc: ${ self:custom.RDSVPC }
    events:
      - http:
          path: hello
          method: get
          private: true
          authorizer: ${ self:custom.authorizer }

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${ self:service }-${ self:provider.stage }
        Description: ServerlessExample